@echo off
rem Build graph.html from graph.json and open it in the default browser.
rem graph.json is regenerated by tools\build_index.py at every register change,
rem so this viewer is always current after a registrar rebuild.
cd /d "%~dp0"
python tools\graph_viewer.py
if errorlevel 1 (
    echo.
    echo Build failed - see message above.
    pause
    exit /b 1
)
start "" graph.html
