"""Build INDEX.md and TRACEABILITY.md from the project registers.

Reads (never edits): requirements.md, DECISIONS.md, OPEN-QUESTIONS.md, RISKS.md,
CHANGELOG.md, 02-solution-concept/solution-concept.md (coverage table),
04-architecture/architecture.md (allocation table, optional - written in phase 04),
05-module-specification/test-cases.md (TC allocation table, optional - written in
phase 05).

Writes (fully generated): INDEX.md, TRACEABILITY.md, graph.json (typed nodes +
typed edges for tools/query_graph.py; register-backed nodes also carry an
'excerpt' - the entry body, whitespace-normalized, capped at 800 chars; the
validator warns on edges pointing at nonexistent register IDs).

Run from the project root:  python tools/build_index.py

Robustness contract (see workshop/agent-navigation-supplement.md, Addition A):
- requirements: table rows `| REQ-### | ... | <priority cell> |` - priority = first word
  of the last cell.
- DECISIONS.md: one marker comment per record, directly under the heading:
  `<!-- DEC-### | <status> | links: ID, ID ... -->`
- OPEN-QUESTIONS.md: table rows `| OQ-### | ... | <status cell> |`.
- RISKS.md: table rows `| RISK-### | ... | <status cell> |`.
- CHANGELOG.md: headings `## [CHG-###] YYYY-MM-DD - <title>`.
- Coverage: rows of the section-4 table in solution-concept.md; the first cell may use
  ranges (REQ-001..008), continuations (REQ-010, 082) and shorthand (REQ-088..090).
- Allocation (optional): the first table under a heading containing "Allocation"
  (any level, case-insensitive) in 04-architecture/architecture.md; rows
  `| REQ-### | SUB-### | IF-### |`, several rows per REQ allowed, `-` in the IF
  cell means submodule-internal (no interface). Whitespace is tolerated, invalid
  rows are skipped (never a crash); a missing file, section or table leaves the
  ARC/IF and SUB columns empty.
- TC allocation (optional): the first table under a heading containing "TC
  allocation" (any level, case-insensitive) in
  05-module-specification/test-cases.md; rows `| TC-### | REQ-### | SUB-### |
  IF-### |`, several rows per TC allowed, `-` in the IF cell allowed. IDs only.
  Whitespace is tolerated, invalid rows are skipped (never a crash); a missing
  file, section or table leaves the TC column empty.
- IF integration coverage (optional, phase 07, finding S-5): the interface
  inventory comes from architecture.md section 3 headings
  `### IF-### - <title>`; a title carrying "(post-R1 boundary)" or
  "(post-MVP boundary)" marks the contract as boundary-pinned (explicitly
  not tested). A test marker is the IF-### token appearing in any test
  source file (`src/tests/**/*.py`, `frontend/tests/**/*.ts`) - a
  tripwire, not a proof: the authoritative per-IF crossing test is named
  in reviews/2026-08-22-phase-07-unit1-review.md. A missing file or section leaves both
  lines with an explicit note instead of failing the build.

Linter/type-checker policy: this is a small, single-purpose utility with the
documented robustness contract above. Strict type-annotation and style warnings
are intentionally suppressed file-wide (comments below) so the workspace
diagnostic counter stays meaningful for real code (phase 04+).
"""
# type: ignore
# ruff: noqa
# pyright: basic

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GEN = "<!-- GENERATED by tools/build_index.py - do not edit by hand -->"


def read(rel):
    return (ROOT / rel).read_text(encoding="utf-8")


def _read_optional(rel):
    """Like read(), but returns '' when the file does not exist yet -
    for registers a young project may not have created (robustness
    contract: a missing register leaves its section empty, never a crash)."""
    path = ROOT / rel
    return path.read_text(encoding="utf-8") if path.exists() else ""


def short(text, n=140):
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


# excerpt cap for graph.json node bodies (entry text, whitespace-normalized)
EXCERPT_MAX = 800


# ---------------------------------------------------------------- parsers

def parse_requirements():
    path = ROOT / "01-requirements/requirements.md"
    if not path.exists():
        return []
    reqs = []
    for m in re.finditer(r"^\| (REQ-0*[1-9]\d*) \|([^|]+)\|([^|]+)\| ([^|]+) \|$",
                         path.read_text(encoding="utf-8"), re.M):
        rid, statement, criteria, prio = m.groups()
        reqs.append({
            "id": rid,
            "title": short(statement),
            # entry body = full statement + acceptance-criteria cell
            "excerpt": short(statement.strip() + " " + criteria.strip(),
                             EXCERPT_MAX),
            "prio": prio.strip().split()[0].rstrip("*"),
        })
    return reqs


def parse_decisions():
    path = ROOT / "DECISIONS.md"
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    markers = {m.group(1): {"status": m.group(2).strip(),
                            "links": m.group(3).strip()}
               for m in re.finditer(
                   r"<!-- (DEC-0*[1-9]\d*) \| ([^|]+) \| links: ([^>]*)-->", text)}
    decs = []
    for m in re.finditer(r"(?ms)^## \[(DEC-0*[1-9]\d*)\] (\d{4}-\d{2}-\d{2}) - (.+?)$"
                         r"(.*?)(?=^## \[DEC-|\Z)", text):
        did, date, title, body = m.groups()
        info = markers.get(did, {"status": "?", "links": ""})
        # entry body = the record's bullets; the machine-readable marker
        # comment line and the Supersedes:/Amends: relation markers are
        # metadata, not text
        body = re.sub(r"(?m)^\s*<!--.*?-->\s*$", "", body)
        body = re.sub(r"(?im)^-\s*(?:Supersedes|Amends):[^\n]*$", "", body)
        decs.append({"id": did, "date": date, "title": short(title.strip(), 180),
                     "excerpt": short(body, EXCERPT_MAX),
                     "status": info["status"], "links": info["links"]})
    missing = [d["id"] for d in decs if d["id"] not in markers]
    if missing:
        print(f"WARN: DECs without marker: {', '.join(missing)}", file=sys.stderr)
    return decs


def parse_open_questions():
    oqs = []
    path = ROOT / "OPEN-QUESTIONS.md"
    if not path.exists():
        return oqs
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| OQ-"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3 or not re.fullmatch(r"OQ-0*[1-9]\d*", cells[0]):
            continue
        # robust against literal pipes inside cells: id = first, question = second,
        # status = last cell
        mid = " | ".join(c for c in cells[2:-2] if c)
        oqs.append({"id": cells[0],
                    "title": short(cells[1]),
                    # entry body = question + resolve-by/answer cell(s)
                    "excerpt": short(cells[1] + (" | Resolve by: " + mid
                                                 if mid else ""), EXCERPT_MAX),
                    "status": cells[-1].replace("*", "").strip()})
    return oqs


def parse_risks():
    risks = []
    path = ROOT / "RISKS.md"
    if not path.exists():
        return risks
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| RISK-"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3 or not re.fullmatch(r"RISK-0*[1-9]\d*", cells[0]):
            continue
        # description + mitigation (third cell from the right; robust from
        # the right against literal pipes in the description)
        body = cells[1] + (" Mitigation: " + cells[-3] if len(cells) >= 6 else "")
        risks.append({"id": cells[0],
                      "title": short(cells[1]),
                      "excerpt": short(body, EXCERPT_MAX),
                      "status": cells[-1].replace("*", "").strip()})
    return risks


def parse_changelog():
    chgs = []
    for m in re.finditer(r"(?ms)^## \[(CHG-0*[1-9]\d*[a-z]?)\] (\d{4}-\d{2}-\d{2}) - "
                         r"(.+?)$(.*?)(?=^## |\Z)", _read_optional("CHANGELOG.md")):
        chgs.append({"id": m.group(1), "date": m.group(2),
                     "title": short(m.group(3).strip(), 180),
                     # entry body = the entry's bullet block (Reason, Change, ...)
                     "excerpt": short(m.group(4), EXCERPT_MAX)})
    return chgs


def expand_reqs(cell):
    """'REQ-001..008' / 'REQ-010, 082' / 'REQ-088..090' / 'REQ-014, 083..087' -> list."""
    out = []
    for m in re.finditer(r"REQ-(\d{3})\.\.(\d{3})", cell):
        out += [f"REQ-{i:03d}" for i in range(int(m.group(1)), int(m.group(2)) + 1)]
    cell = re.sub(r"REQ-\d{3}\.\.\d{3}", "", cell)
    # continuation ranges without the REQ prefix, e.g. ", 083..087"
    for m in re.finditer(r"(?:^|,)\s*(\d{3})\.\.(\d{3})", cell):
        out += [f"REQ-{i:03d}" for i in range(int(m.group(1)), int(m.group(2)) + 1)]
    cell = re.sub(r"(?:^|,)\s*\d{3}\.\.\d{3}", "", cell)
    nums = []
    for part in cell.split(","):
        nums += re.findall(r"\d{3}", part)
    out += [f"REQ-{n}" for n in nums]
    seen, res = set(), []
    for r in out:
        if r not in seen:
            seen.add(r)
            res.append(r)
    return res


def parse_coverage():
    """solution-concept.md section 4 table -> {REQ-###: 'SC 3.x/3.y'}

    Returns {} when the file or the section does not exist yet
    (pre-phase-02), so the coverage column stays empty instead of
    failing the build."""
    path = ROOT / "02-solution-concept/solution-concept.md"
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    parts = text.split("## 4. Requirements coverage", 1)
    if len(parts) < 2:
        return {}
    sec = parts[1].split("\n## ", 1)[0]
    cov = {}
    for m in re.finditer(r"^\| (REQ-[^|]+) \| ([^|]+) \|$", sec, re.M):
        reqs, target = m.group(1), m.group(2)
        sections = re.findall(r"\d\.\d+", target)
        if not sections:
            continue
        ref = "SC " + "/".join(sections)
        for rid in expand_reqs(reqs):
            cov[rid] = ref
    return cov


def parse_allocations():
    """architecture.md allocation table -> {REQ-###: {'sub': [...], 'if': [...]}}

    Returns {} when the file or the table does not exist yet (pre-phase-04),
    so the ARC/IF and SUB columns stay empty instead of failing the build.
    """
    path = ROOT / "04-architecture/architecture.md"
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    # first heading whose text contains "allocation" (any level, any exact name)
    head = re.search(r"^#{1,6}\s+.*allocation.*$", text, re.M | re.I)
    if not head:
        return {}
    sec = text[head.end():]
    nxt = re.search(r"^#{1,6}\s", sec, re.M)
    if nxt:
        sec = sec[:nxt.start()]
    alloc = {}
    for line in sec.splitlines():
        if not line.lstrip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 3:
            continue
        rid, sub, iff = cells
        # header, separator and malformed rows are skipped, never fatal
        if not re.fullmatch(r"REQ-\d{3}", rid):
            continue
        if not re.fullmatch(r"SUB-\d{3}", sub):
            continue
        if iff != "-" and not re.fullmatch(r"IF-\d{3}", iff):
            continue
        entry = alloc.setdefault(rid, {"sub": [], "if": []})
        if sub not in entry["sub"]:
            entry["sub"].append(sub)
        if iff != "-" and iff not in entry["if"]:
            entry["if"].append(iff)
    return alloc


def parse_tc_allocations():
    """test-cases.md TC allocation table -> [{'tc', 'req', 'sub', 'if'}, ...]

    Returns [] when the file or the table does not exist yet (pre-phase-05),
    so the TC column stays empty instead of failing the build.
    """
    path = ROOT / "05-module-specification/test-cases.md"
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    # first heading whose text contains "tc allocation" (any level, any name)
    head = re.search(r"^#{1,6}\s+.*tc allocation.*$", text, re.M | re.I)
    if not head:
        return []
    sec = text[head.end():]
    nxt = re.search(r"^#{1,6}\s", sec, re.M)
    if nxt:
        sec = sec[:nxt.start()]
    rows = []
    for line in sec.splitlines():
        if not line.lstrip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 4:
            continue
        tc, rid, sub, iff = cells
        # header, separator and malformed rows are skipped, never fatal
        if not re.fullmatch(r"TC-\d{3}", tc):
            continue
        if not re.fullmatch(r"REQ-\d{3}", rid):
            continue
        if not re.fullmatch(r"SUB-\d{3}", sub):
            continue
        if iff != "-" and not re.fullmatch(r"IF-\d{3}", iff):
            continue
        rows.append({"tc": tc, "req": rid, "sub": sub, "if": iff})
    return rows


def parse_if_register():
    """architecture.md section 3 -> {'ifs': [IF-###...], 'pinned': [IF-###...],
    'excerpts': {IF-###: entry body}}

    Returns {'ifs': [], 'pinned': [], 'excerpts': {}} when the file or section
    does not exist (pre-phase-04), so the coverage lines show a note instead of
    failing the build.
    """
    path = ROOT / "04-architecture/architecture.md"
    result = {"ifs": [], "pinned": [], "excerpts": {}}
    if not path.exists():
        return result
    text = path.read_text(encoding="utf-8")
    head = re.search(r"^## 3\. Interface register.*$", text, re.M)
    if not head:
        return result
    sec = text[head.end():]
    nxt = re.search(r"^## \d", sec, re.M)
    if nxt:
        sec = sec[: nxt.start()]
    for m in re.finditer(r"(?ms)^### (IF-\d{3}) - (.+?)$(.*?)(?=^### |\Z)", sec):
        iid, title, body = m.group(1), m.group(2), m.group(3)
        result["ifs"].append(iid)
        result["excerpts"][iid] = short(body, EXCERPT_MAX)
        if re.search(r"\(post-(R1|MVP) boundary\)", title):
            result["pinned"].append(iid)
    return result


def parse_sub_excerpts():
    """architecture.md section 2 submodule register -> {SUB-###: entry body}.

    Returns {} when the file or section does not exist yet (pre-phase-04)."""
    path = ROOT / "04-architecture/architecture.md"
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    head = re.search(r"^## \d+\. Submodule register.*$", text, re.M | re.I)
    if not head:
        return {}
    sec = text[head.end():]
    nxt = re.search(r"^## \d", sec, re.M)
    if nxt:
        sec = sec[: nxt.start()]
    out = {}
    for m in re.finditer(r"(?ms)^### (SUB-\d{3}) - .+?$(.*?)(?=^### |\Z)", sec):
        out[m.group(1)] = short(m.group(2), EXCERPT_MAX)
    return out


def parse_tc_register():
    """test-cases.md TC register table -> {TC-###: scenario cell}.

    Returns {} when the file or the table does not exist yet (pre-phase-05).
    The scenario (last cell) is the entry body; the TC allocation table parsed
    by parse_tc_allocations carries IDs only."""
    path = ROOT / "05-module-specification/test-cases.md"
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    head = re.search(r"^#{1,6}\s+.*tc register.*$", text, re.M | re.I)
    if not head:
        return {}
    sec = text[head.end():]
    nxt = re.search(r"^#{1,6}\s", sec, re.M)
    if nxt:
        sec = sec[: nxt.start()]
    out = {}
    for line in sec.splitlines():
        if not line.lstrip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 3:
            continue
        if not re.fullmatch(r"TC-\d{3}", cells[0]):
            continue
        out.setdefault(cells[0], short(cells[-1], EXCERPT_MAX))
    return out


def parse_fr_excerpts():
    """product/FEATURE-REQUESTS.md register -> {FR-###: entry body}.

    Returns {} when the file or the Register section does not exist. The
    template's literal 'FR-###' placeholder never matches \\d{3}."""
    path = ROOT / "product/FEATURE-REQUESTS.md"
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    head = re.search(r"^## Register.*$", text, re.M)
    sec = text[head.end():] if head else text
    out = {}
    for m in re.finditer(r"(?ms)^### (FR-\d{3}) - .+?$(.*?)(?=^### |^## |\Z)",
                         sec):
        out[m.group(1)] = short(m.group(2), EXCERPT_MAX)
    return out


def parse_agenda_item_excerpts():
    """decision-meetings/*.md -> {M-###: entry body}.

    Meeting files carry '## M-### - <title>' verdict records, agenda.md carries
    '### M-### - <title> [decided ...]' proposal records. Files are scanned in
    sorted order (meeting files sort before agenda.md) and the first occurrence
    wins, so a meeting verdict body beats the agenda proposal body."""
    out = {}
    d = ROOT / "decision-meetings"
    if not d.exists():
        return out
    for path in sorted(d.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        for m in re.finditer(r"(?ms)^#{2,3} (M-\d{3}) - .+?$(.*?)(?=^#{2,3} |\Z)",
                             text):
            out.setdefault(m.group(1), short(m.group(2), EXCERPT_MAX))
    return out


def scan_if_test_markers():
    """IF-### tokens in test sources (src/tests/**/*.py, frontend/tests/**/*.ts)."""
    found = set()
    for pattern in ("src/tests/**/*.py", "frontend/tests/**/*.ts"):
        for path in sorted(ROOT.glob(pattern)):
            if "__pycache__" in path.parts:
                continue
            found |= set(re.findall(r"IF-\d{3}",
                                    path.read_text(encoding="utf-8")))
    return found


# ---------------------------------------------------------------- outputs

def build_index(reqs, decs, oqs, risks, chgs, tc_rows):
    lines = [
        "# Index",
        "",
        GEN,
        "Regenerate: `python tools/build_index.py` from the project root.",
        "One line per entity; read this before opening any register in full.",
        "",
        f"Counts: {len(reqs)} REQ | {len(decs)} DEC | {len(oqs)} OQ "
        f"({sum(1 for o in oqs if 'resolved' in o['status'].lower())} resolved) | "
        f"{len(risks)} RISK | {len(chgs)} CHG entries",
        "",
        "## Requirements (REQ -> requirements.md)",
        "",
    ]
    for r in reqs:
        lines.append(f"- {r['id']} | {r['prio']} | {r['title']}")
    lines += ["", "## Decisions (DEC -> DECISIONS.md)", ""]
    for d in decs:
        link = f" | links: {d['links']}" if d["links"] else ""
        lines.append(f"- {d['id']} | {d['status']} | {d['date']} | {d['title']}{link}")
    lines += ["", "## Open questions (OQ -> OPEN-QUESTIONS.md)", ""]
    for o in oqs:
        lines.append(f"- {o['id']} | {o['status']} | {o['title']}")
    lines += ["", "## Risks (RISK -> RISKS.md)", ""]
    for r in risks:
        lines.append(f"- {r['id']} | {r['status']} | {r['title']}")
    lines += ["", "## Change log (CHG -> CHANGELOG.md, newest first)", ""]
    for c in chgs:
        lines.append(f"- {c['id']} | {c['date']} | {c['title']}")
    lines += ["", "## Test cases (TC -> 05-module-specification/test-cases.md)", ""]
    for t in tc_rows:
        lines.append(f"- {t['tc']} | {t['req']} | {t['sub']}")
    lines.append("")
    return "\n".join(lines)


def build_traceability(reqs, cov, alloc, tc_rows, if_reg):
    tc_by_req = {}
    for t in tc_rows:
        tc_by_req.setdefault(t["req"], [])
        if t["tc"] not in tc_by_req[t["req"]]:
            tc_by_req[t["req"]].append(t["tc"])
    req_ids = {r["id"] for r in reqs}
    alloc_pairs = {(rid, s) for rid, a in alloc.items() for s in a["sub"]}
    lines = [
        "# Traceability Matrix",
        "",
        GEN,
        "Regenerate: `python tools/build_index.py` from the project root.",
        "The Solution column is a projection of the coverage table in",
        "`02-solution-concept/solution-concept.md` (section 4); the ARC/IF and SUB",
        "columns are a projection of the allocation table in",
        "`04-architecture/architecture.md` (Allocation section); the Test case (TC)",
        "column is a projection of the TC allocation table in",
        "`05-module-specification/test-cases.md` - edit them there, then rebuild.",
        "",
        "Links each requirement through the whole V so nothing is unbuilt or unverified.",
        "",
        "| REQ | Solution | Architecture (ARC/IF) | Submodule (SUB) | Test case (TC) | Validation test | Status |",
        "|-----|----------|-----------------------|-----------------|----------------|-----------------|--------|",
    ]
    for r in reqs:
        ref = cov.get(r["id"], "")
        a = alloc.get(r["id"], {"sub": [], "if": []})
        sub = ", ".join(a["sub"])
        arc = ", ".join(a["if"])
        tcs = ", ".join(tc_by_req.get(r["id"], []))
        # empty cells render as "| |" so a missing allocation or TC table leaves
        # the row byte-identical to the pre-phase-04 format
        arc_cell = f" {arc} " if arc else " "
        sub_cell = f" {sub} " if sub else " "
        tc_cell = f" {tcs} " if tcs else " "
        if tcs:
            status = "specced"
        elif sub:
            status = "allocated"
        elif ref:
            status = "concept"
        else:
            status = "open"
        lines.append(
            f"| {r['id']} | {ref} |{arc_cell}|{sub_cell}|{tc_cell}| | {status} |")
    no_sub = [r["id"] for r in reqs if r["id"] in cov and r["id"] not in alloc]
    no_tc = [rid for rid in alloc if rid not in tc_by_req]
    orphans = [f"{t['tc']} ({t['req']}/{t['sub']})" for t in tc_rows
               if t["req"] not in req_ids or (t["req"], t["sub"]) not in alloc_pairs]
    lines += [
        "",
        "## Coverage checks (auto-filled)",
        "- Requirements with no allocated submodule: "
        f"{', '.join(no_sub) if no_sub else 'none'}",
        "- Requirements with no test case: "
        f"{', '.join(no_tc) if no_tc else 'none'}",
        "- Test cases with no parent requirement (orphans): "
        f"{', '.join(orphans) if orphans else 'none'}",
    ]
    if not if_reg["ifs"]:
        lines.append("- Interfaces (IF-###) with no integration test: "
                     "(interface register not found - not computed)")
    else:
        tested = scan_if_test_markers()
        gaps = [i for i in if_reg["ifs"]
                if i not in tested and i not in if_reg["pinned"]]
        lines.append("- Interfaces (IF-###) with no integration test: "
                     f"{', '.join(gaps) if gaps else 'none'}")
        lines.append("- Interfaces (IF-###) boundary-pinned "
                     "(post-R1/post-MVP, not tested): "
                     f"{', '.join(if_reg['pinned']) if if_reg['pinned'] else 'none'}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------- graph export
#
# graph.json is a derived view only - every edge comes from a source the
# parsers above (or the small dedicated readers below) already trust. No new
# register formats; the single new convention: keep IDs machine-readable in
# CHANGELOG "Affected artifacts" lines (CHG-135).

ID_TOKEN = re.compile(
    r"\b(?:REQ|DEC|OQ|RISK|CHG|TC|SUB|IF|ARC|FR|M|D)-\d{1,3}[a-z]?\b")

PREFIX_TYPE = {"REQ": "requirement", "DEC": "decision", "OQ": "question",
               "RISK": "risk", "CHG": "change", "TC": "test-case",
               "SUB": "submodule", "IF": "interface", "ARC": "architecture",
               "FR": "feature-request", "M": "agenda-item", "D": "directive"}

# prefixes that live in parsed registers; edges to unknown ones are validator
# warnings (typo detector). Other prefixes get implicit nodes, no warning.
REGISTER_PREFIXES = ("REQ", "DEC", "OQ", "RISK", "CHG", "TC", "SUB", "IF")


def extract_ids(text):
    """Machine-readable ID tokens, expanding ranges (DEC-025..031, FR-001..007)
    and slash shorthand (REQ-021/053/058). Order-preserving, deduped."""
    ids = []

    def add(tok):
        if tok not in ids:
            ids.append(tok)

    for m in re.finditer(r"\b([A-Z]{2,4})-(\d{3})\.\.(?:[A-Z]{2,4}-)?(\d{3})\b",
                         text):
        prefix, a, b = m.group(1), int(m.group(2)), int(m.group(3))
        if 0 <= b - a <= 50:
            for i in range(a, b + 1):
                add(f"{prefix}-{i:03d}")
    text = re.sub(r"\b[A-Z]{2,4}-\d{3}\.\.(?:[A-Z]{2,4}-)?\d{3}\b", " ", text)
    for m in re.finditer(r"\b([A-Z]{2,4})-(\d{3})((?:/\d{3})+)", text):
        prefix = m.group(1)
        add(f"{prefix}-{m.group(2)}")
        for n in re.findall(r"\d{3}", m.group(3)):
            add(f"{prefix}-{n}")
    text = re.sub(r"\b[A-Z]{2,4}-\d{3}(?:/\d{3})+", " ", text)
    for tok in ID_TOKEN.findall(text):
        add(tok)
    return ids


def parse_oq_resolutions():
    """OPEN-QUESTIONS.md -> {OQ-###: [DEC-###...]} for resolved questions.

    The DEC reference sits in the 'Resolve by' cell (third column); because
    literal pipes inside the question cell can shift columns, all cells between
    question and the last two (Affects, Status) are scanned. Only rows whose
    status cell says resolved contribute 'closes' edges.
    """
    out = {}
    for line in _read_optional("OPEN-QUESTIONS.md").splitlines():
        if not line.startswith("| OQ-"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3 or not re.fullmatch(r"OQ-0*[1-9]\d*", cells[0]):
            continue
        if "resolved" not in cells[-1].lower():
            continue
        mid = " | ".join(cells[2:-2])
        decs = sorted(set(re.findall(r"DEC-\d{3}", mid)))
        if decs:
            out[cells[0]] = decs
    return out


def parse_dec_body_relations():
    """DECISIONS.md -> {DEC-###: {'amends': [...], 'supersedes': [...]}}.
    Primary source is the explicit machine-readable marker line
    `- Supersedes: DEC-###[, DEC-### ...]` (and the `- Amends:` analogue),
    anchored 2026-09-13 (owner decision, methods chat). Prose harvesting
    ('amends DEC-###', 'DEC-### superseded by this DEC') stays as the legacy
    fallback for pre-convention entries; it is conservative by design (option-
    menu phrasing like 'superseded versions retained' carries no DEC id).
    The marker `links:` list carries no relation type, so only these explicit
    relations upgrade a DEC->DEC edge from the generic 'links'."""
    out = {}
    for m in re.finditer(r"(?ms)^## \[(DEC-\d{3})\].*?$(.*?)(?=^## \[DEC-|\Z)",
                         read("DECISIONS.md")):
        did, body = m.group(1), m.group(2)
        rel = {"amends": set(), "supersedes": set()}
        for mm in re.finditer(r"(?im)^-\s*(Supersedes|Amends):\s*([^\n()]*)",
                              body):
            kind = "supersedes" if mm.group(1).lower() == "supersedes" else "amends"
            rel[kind].update(re.findall(r"DEC-\d{3}", mm.group(2)))
        for mm in re.finditer(r"(?i)\b(amend(?:s|ing)?|supersedes?)\s+(?:of\s+|to\s+)?(DEC-\d{3})",
                              body):
            rel["amends" if mm.group(1).lower().startswith("amend")
                else "supersedes"].add(mm.group(2))
        for mm in re.finditer(r"(?i)(DEC-\d{3})[^.\n]{0,60}?\b(superseded|amended) by this DEC\b",
                              body):
            rel["supersedes" if mm.group(2) == "superseded"
                else "amends"].add(mm.group(1))
        if rel["amends"] or rel["supersedes"]:
            out[did] = {k: sorted(v) for k, v in rel.items() if v}
    return out


def parse_chg_affects():
    """CHANGELOG.md -> {CHG-###: [ID...]} from each entry's 'Affected artifacts'
    block (the bullet plus its wrapped continuation lines). Wrapped lines are
    re-joined without a space after a trailing '/' or '-' so mid-token wraps
    stay machine-readable."""
    out = {}
    for sec in re.split(r"(?m)^## ", _read_optional("CHANGELOG.md")):
        m = re.match(r"\[(CHG-0*[1-9]\d*[a-z]?)\]", sec)
        if not m:
            continue
        cid = m.group(1)
        bm = re.search(r"(?ms)^- Affected artifacts:\s*(.*?)(?=^- [A-Z]|\Z)", sec)
        if not bm:
            continue
        joined = ""
        for ln in (l.strip() for l in bm.group(1).splitlines() if l.strip()):
            if joined.endswith(("/", "-")):
                joined += ln
            else:
                joined += (" " if joined else "") + ln
        bucket = out.setdefault(cid, [])
        for tok in extract_ids(joined):
            if tok != cid and tok not in bucket:
                bucket.append(tok)
    return out


def parse_releases():
    """RELEASES.md -> {'releases': [{'id', 'title'}], 'edges': {REQ-###: R-id}}.

    Conservative by design (the file is prose, not a register table): only
    scope-defining lines are harvested - 'Touches:' lines, '**... scope:**'
    lines, lines that START with a REQ token (after optional 'Also here:'
    prefix and bold markers), pure number-continuation lines (', 051, 053 ...')
    and table rows whose first cell holds REQ tokens (the R1 SHOULD table).
    Prose like 'Deliberately not in R1: REQ-058 ...' is therefore NOT an edge.
    Enumeration lists that wrap mid-list are followed via a continuation
    state (open line ends with ',' or an unbalanced parenthesis); on such
    continuation lines only REQ tokens OUTSIDE parentheses are harvested, so
    asides like '(REQ-085 was listed here until ...)' stay out.
    First mention wins (a REQ lands in exactly one release).
    """
    path = ROOT / "RELEASES.md"
    if not path.exists():
        return {"releases": [], "edges": {}}
    text = path.read_text(encoding="utf-8")
    releases, edges = [], {}
    for m in re.finditer(r"(?ms)^## (R\d+(?:\.\d+)?)\s*-\s*(.+?)$(.*?)(?=^## |\Z)",
                         text):
        rid, title, body = m.group(1), m.group(2).strip(), m.group(3)
        releases.append({"id": rid, "title": short(title, 120)})
        cont = False
        for line in body.splitlines():
            s = line.strip()
            if not s:
                cont = False
                continue
            harvest = None
            trigger = False
            if s.startswith("|"):
                cells = [c.strip() for c in s.strip("|").split("|")]
                if cells and re.search(r"REQ-\d{3}", cells[0]):
                    harvest, trigger = cells[0], True
            else:
                sm = re.match(r"\*\*[^*]*\bscope:\*\*\s*(.*)$", s)
                t = sm.group(1) if sm else s.lstrip("* ")
                for pre in ("Touches:", "Also here:"):
                    if t.startswith(pre):
                        t = t[len(pre):].lstrip("* ")
                if re.match(r"REQ-\d{3}", t) or (
                        re.fullmatch(r"[\d.,\s]+", t) and re.search(r"\d{3}", t)):
                    harvest, trigger = t, True
            if trigger:
                # scope-defining line: ranges and bare-number continuations
                for req in expand_reqs(harvest):
                    edges.setdefault(req, rid)
            elif cont:
                # wrapped enumeration line: explicit REQ tokens only, and only
                # outside parentheses (prose asides like '(REQ-085 was listed
                # here until ...)' or OQ/DEC references must not become edges)
                aside = re.sub(r"\([^()]*\)", " ", s)
                for mm in re.finditer(r"REQ-(\d{3})((?:/\d{3})*)", aside):
                    edges.setdefault(f"REQ-{mm.group(1)}", rid)
                    for n in re.findall(r"\d{3}", mm.group(2)):
                        edges.setdefault(f"REQ-{n}", rid)
            cont = ((trigger or cont)
                    and (s.rstrip().endswith(",")
                         or s.count("(") != s.count(")")))
    return {"releases": releases, "edges": edges}


def scan_if_test_marker_files():
    """IF-### token -> set of test files carrying it (same scan scope as
    scan_if_test_markers; POSIX-style relative paths for stable output)."""
    found = {}
    for pattern in ("src/tests/**/*.py", "frontend/tests/**/*.ts"):
        for path in sorted(ROOT.glob(pattern)):
            if "__pycache__" in path.parts:
                continue
            rel = str(path.relative_to(ROOT)).replace("\\", "/")
            for iid in set(re.findall(r"IF-\d{3}",
                                      path.read_text(encoding="utf-8"))):
                found.setdefault(iid, set()).add(rel)
    return found


def _natkey(nid):
    return tuple(f"{int(p):06d}" if p.isdigit() else p
                 for p in re.split(r"(\d+)", nid))


def build_graph(reqs, decs, oqs, risks, chgs, cov, alloc, tc_rows, if_reg):
    nodes = {}          # id -> {'id', 'type', 'title'?}
    edges = {}          # (from, to, type) -> source ('+'-joined when several)

    def node(nid, ntype, title=None, excerpt=None):
        n = nodes.setdefault(nid, {"id": nid, "type": ntype})
        if title and "title" not in n:
            n["title"] = title
        if excerpt and "excerpt" not in n:
            n["excerpt"] = excerpt

    def implicit(nid):
        if nid not in nodes:
            node(nid, PREFIX_TYPE.get(nid.split("-")[0], "other"))

    def edge(frm, to, etype, source):
        if frm == to:
            return
        key = (frm, to, etype)
        if key in edges:
            if source not in edges[key].split("+"):
                edges[key] += "+" + source
        else:
            edges[key] = source

    for r in reqs:
        node(r["id"], "requirement", r["title"], r.get("excerpt"))
    for d in decs:
        node(d["id"], "decision", d["title"], d.get("excerpt"))
    for o in oqs:
        node(o["id"], "question", o["title"], o.get("excerpt"))
    for r in risks:
        node(r["id"], "risk", r["title"], r.get("excerpt"))
    for c in chgs:
        node(c["id"], "change", c["title"], c.get("excerpt"))
    for t in tc_rows:
        node(t["tc"], "test-case")
    for iid in if_reg["ifs"]:
        node(iid, "interface")

    # duplicate CHG numbers collapse into one node - surface that (S-5 style)
    chg_ids = [c["id"] for c in chgs]
    dupes = sorted({c for c in chg_ids if chg_ids.count(c) > 1})
    if dupes:
        print(f"WARN graph: duplicate CHG ids in CHANGELOG.md: "
              f"{', '.join(dupes)}", file=sys.stderr)

    # --- DEC markers: decides / amends / supersedes / closes / links
    body_rel = parse_dec_body_relations()
    superseded_by = {}
    for d in decs:
        m = re.fullmatch(r"superseded by (DEC-\d{3})", d["status"])
        if m:
            superseded_by[d["id"]] = m.group(1)
    for d in decs:
        for tok in extract_ids(d["links"]):
            implicit(tok)
            prefix = tok.split("-")[0]
            if prefix == "REQ":
                edge(d["id"], tok, "decides", "dec-links")
            elif prefix == "OQ":
                edge(tok, d["id"], "closes", "dec-links")
            elif prefix == "DEC":
                if superseded_by.get(tok) == d["id"] or (
                        tok in body_rel.get(d["id"], {}).get("supersedes", [])):
                    edge(d["id"], tok, "supersedes", "dec-links")
                elif tok in body_rel.get(d["id"], {}).get("amends", []):
                    edge(d["id"], tok, "amends", "dec-links")
                else:
                    edge(d["id"], tok, "links", "dec-links")
            else:
                edge(d["id"], tok, "links", "dec-links")

    # --- closes from the OQ status cell
    for oq, dlist in parse_oq_resolutions().items():
        for did in dlist:
            implicit(did)
            edge(oq, did, "closes", "oq-status")

    # --- covers: REQ -> concept section ('SC 3.4/3.5' splits into two edges)
    for rid, ref in cov.items():
        for sec in ref[3:].split("/"):
            sid = f"SC {sec}"
            node(sid, "section")
            edge(rid, sid, "covers", "coverage-table")

    # --- allocated_to: REQ -> SUB / IF
    for rid, a in alloc.items():
        for s in a["sub"]:
            implicit(s)
            edge(rid, s, "allocated_to", "allocation-table")
        for i in a["if"]:
            implicit(i)
            edge(rid, i, "allocated_to", "allocation-table")

    # --- tested_by: REQ -> TC (+ REQ -> crossed IF), IF -> test file (marker)
    for t in tc_rows:
        edge(t["req"], t["tc"], "tested_by", "tc-allocation")
        if t["if"] != "-":
            implicit(t["if"])
            edge(t["req"], t["if"], "tested_by", "tc-allocation")
    for iid, files in sorted(scan_if_test_marker_files().items()):
        implicit(iid)
        for f in sorted(files):
            node(f, "test-file")
            edge(iid, f, "tested_by", "test-marker-scan")

    # --- affects: CHG -> machine-readable IDs in 'Affected artifacts'
    for cid, ids in parse_chg_affects().items():
        for tok in ids:
            implicit(tok)
            edge(cid, tok, "affects", "changelog")

    # --- in_release: REQ -> release (conservative RELEASES.md parse)
    rel = parse_releases()
    for r in rel["releases"]:
        node(r["id"], "release", r["title"])
    for req, rid in rel["edges"].items():
        implicit(req)
        edge(req, rid, "in_release", "releases-md")

    # --- register entry excerpts for register-backed nodes without a
    # title-carrying parse above (TC register scenario, IF/SUB section bodies,
    # FR register bodies, M agenda/meeting bodies). Nodes without a register
    # home (sections, releases, test files, implicit IDs) get no excerpt.
    excerpts = {}
    for src in (parse_tc_register(), parse_sub_excerpts(),
                parse_fr_excerpts(), parse_agenda_item_excerpts(),
                if_reg.get("excerpts", {})):
        excerpts.update(src)
    for nid, ex in excerpts.items():
        if ex and nid in nodes:
            nodes[nid]["excerpt"] = ex

    # --- validator: edges to unknown register IDs are consistency warnings
    authoritative = ({r["id"] for r in reqs} | {d["id"] for d in decs} |
                     {o["id"] for o in oqs} | {r["id"] for r in risks} |
                     set(chg_ids) | {t["tc"] for t in tc_rows} |
                     set(if_reg["ifs"]) |
                     {s for a in alloc.values() for s in a["sub"]})
    dangling = {}
    for (frm, to, etype) in edges:
        for ep in (frm, to):
            if (ep.split("-")[0] in REGISTER_PREFIXES
                    and ep not in authoritative):
                dangling.setdefault(ep, []).append(f"{frm}->{to} ({etype})")
    for ep in sorted(dangling, key=_natkey):
        refs = ", ".join(dangling[ep][:3])
        more = f" +{len(dangling[ep]) - 3} more" if len(dangling[ep]) > 3 else ""
        print(f"WARN graph: edge to unknown ID {ep}: {refs}{more}",
              file=sys.stderr)

    node_list = sorted(nodes.values(), key=lambda n: _natkey(n["id"]))
    edge_list = [{"from": f, "to": t, "type": ty, "source": src}
                 for (f, t, ty), src in sorted(
                     edges.items(), key=lambda kv: (_natkey(kv[0][0]), kv[0][2],
                                                    _natkey(kv[0][1])))]
    return {"_generated":
            "GENERATED by tools/build_index.py - do not edit by hand - "
            "regenerate: python tools/build_index.py from the project root",
            "nodes": node_list, "edges": edge_list}


def main():
    reqs = parse_requirements()
    decs = parse_decisions()
    oqs = parse_open_questions()
    risks = parse_risks()
    chgs = parse_changelog()
    cov = parse_coverage()
    alloc = parse_allocations()
    tc_rows = parse_tc_allocations()

    if_reg = parse_if_register()

    (ROOT / "INDEX.md").write_text(build_index(reqs, decs, oqs, risks, chgs, tc_rows),
                                   encoding="utf-8")
    (ROOT / "TRACEABILITY.md").write_text(
        build_traceability(reqs, cov, alloc, tc_rows, if_reg),
        encoding="utf-8")

    graph = build_graph(reqs, decs, oqs, risks, chgs, cov, alloc, tc_rows,
                        if_reg)
    (ROOT / "graph.json").write_text(
        json.dumps(graph, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8")
    type_counts = {}
    for e in graph["edges"]:
        type_counts[e["type"]] = type_counts.get(e["type"], 0) + 1
    n_excerpt = sum(1 for n in graph["nodes"] if n.get("excerpt"))
    print(f"graph: {len(graph['nodes'])} nodes | {len(graph['edges'])} edges "
          f"({', '.join(f'{t} {n}' for t, n in sorted(type_counts.items()))}) | "
          f"excerpts {n_excerpt}")

    gaps = [i for i in if_reg["ifs"]
            if i not in scan_if_test_markers() and i not in if_reg["pinned"]]
    print(f"IF {len(if_reg['ifs'])} (pinned {len(if_reg['pinned'])}) | "
          f"no integration test: {', '.join(gaps) if gaps else 'none'}")

    print(f"REQ {len(reqs)} | DEC {len(decs)} | OQ {len(oqs)} | RISK {len(risks)} "
          f"| CHG {len(chgs)} | covered {len(cov)} | allocated {len(alloc)}")
    missing = [r["id"] for r in reqs if r["id"] not in cov]
    print(f"uncovered (status open): {', '.join(missing) if missing else 'none'}")


if __name__ == "__main__":
    main()
