#!/usr/bin/env python3
"""Build a self-contained interactive HTML view of graph.json.

Usage:
  python tools/graph_viewer.py            # writes graph.html at the repo root

Reads graph.json (generated by tools/build_index.py) and embeds the data
inline - the resulting graph.html has zero external dependencies and works
offline via file:// (double-click). graph.json is never modified.

Exit 1 on missing graph.json. Python stdlib only.
"""
# type: ignore
# ruff: noqa
# pyright: basic

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# node fill color per ID prefix (first letters before '-'), else "other"
COLORS = {
    "REQ": "#4c8dff", "DEC": "#b06fe0", "CHG": "#f0a53c", "OQ": "#e05c5c",
    "TC": "#3fbf7f", "IF": "#3fbfc9", "SUB": "#8f7bf0", "FR": "#e0709a",
    "M": "#c2c94a", "RISK": "#e07b3f", "other": "#9aa0a6",
}

HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>relation graph</title>
<style>
  :root { --bg: #14171c; --panel: #1c2129; --border: #2c333d; --fg: #d8dee6;
          --dim: #8a939e; }
  * { box-sizing: border-box; }
  html, body { margin: 0; height: 100%; overflow: hidden; background: var(--bg);
    color: var(--fg); font: 13px/1.45 "Segoe UI", system-ui, sans-serif; }
  #canvas { display: block; width: 100%; height: 100%; cursor: grab; }
  #canvas.grabbing { cursor: grabbing; }
  .box { position: fixed; background: var(--panel); border: 1px solid var(--border);
    border-radius: 6px; padding: 10px 12px; }
  #searchbox { top: 10px; left: 10px; width: 300px; }
  #search { width: calc(100% - 70px); background: #12151a; color: var(--fg);
    border: 1px solid var(--border); border-radius: 4px; padding: 4px 8px; }
  #search:focus { outline: none; border-color: #4c8dff; }
  #matchinfo { color: var(--dim); margin-left: 8px; }
  #legend { top: 10px; right: 10px; }
  #legend h3, #filters h3 { margin: 0 0 6px; font-size: 11px;
    text-transform: uppercase; letter-spacing: .06em; color: var(--dim); }
  #legend .row { display: flex; align-items: center; gap: 6px; margin: 2px 0; }
  #legend .dot { width: 10px; height: 10px; border-radius: 50%; flex: none; }
  #filters { top: 0; right: 0; }
  #legendwrap { position: fixed; top: 10px; right: 10px; display: flex;
    flex-direction: column; gap: 8px; max-width: 170px; }
  #legend, #filters { position: static; }
  #filters label { display: flex; align-items: center; gap: 6px; margin: 2px 0;
    white-space: nowrap; cursor: pointer; }
  #sidepanel { top: 64px; left: 10px; bottom: 10px; width: 340px; padding: 0;
    display: none; flex-direction: column; overflow: hidden; }
  #sidepanel.open { display: flex; }
  #sp-head { padding: 10px 12px; border-bottom: 1px solid var(--border); }
  #sp-id { font-weight: 600; font-size: 15px; }
  #sp-type { color: var(--dim); }
  #sp-title { margin-top: 4px; }
  #sp-excerpt { margin-top: 6px; white-space: pre-wrap; word-wrap: break-word;
    font-size: 12px; line-height: 1.5; color: var(--fg);
    max-height: 200px; overflow-y: auto; }
  #sp-close { float: right; cursor: pointer; color: var(--dim); border: none;
    background: none; font-size: 15px; }
  #sp-close:hover { color: var(--fg); }
  #sp-body { overflow-y: auto; padding: 8px 12px; flex: 1; }
  #sp-body h4 { margin: 10px 0 4px; font-size: 11px; text-transform: uppercase;
    letter-spacing: .06em; color: var(--dim); }
  .edge-group { margin: 3px 0; }
  .edge-type { color: var(--dim); margin-right: 4px; }
  a.node-link { color: #7fb2ff; text-decoration: none; cursor: pointer; }
  a.node-link:hover { text-decoration: underline; }
  #status { position: fixed; bottom: 8px; left: 10px; color: var(--dim); }
</style>
</head>
<body>
<canvas id="canvas"></canvas>
<div class="box" id="searchbox">
  <input id="search" placeholder="Search ID or fragment (e.g. REQ-053)" autofocus>
  <span id="matchinfo"></span>
</div>
<div id="legendwrap">
  <div class="box" id="legend"><h3>Node types</h3><div id="legendrows"></div></div>
  <div class="box" id="filters"><h3>Edge types</h3><div id="filterrows"></div></div>
</div>
<div class="box" id="sidepanel">
  <div id="sp-head">
    <button id="sp-close" title="Close">&#10005;</button>
    <span id="sp-id"></span> <span id="sp-type"></span>
    <div id="sp-title"></div>
    <div id="sp-excerpt"></div>
  </div>
  <div id="sp-body"></div>
</div>
<div id="status"></div>
<script id="graph-data" type="application/json">__DATA__</script>
<script>
"use strict";

// ---- data ---------------------------------------------------------------
const G = JSON.parse(document.getElementById("graph-data").textContent);
const COLORS = __COLORS__;

const byId = new Map();
G.nodes.forEach((n, i) => { n.index = i; byId.set(n.id, n); });

// adjacency: id -> [{dir:'->'|'<-', type, other}] for the side panel
const adj = new Map(G.nodes.map(n => [n.id, []]));
G.edges.forEach(e => {
  adj.get(e.from).push({ dir: "->", type: e.type, other: e.to });
  adj.get(e.to).push({ dir: "<-", type: e.type, other: e.from });
});

const edgeTypes = [...new Set(G.edges.map(e => e.type))].sort();
const visibleTypes = new Set(edgeTypes);

function prefix(id) {
  // ID prefix = leading uppercase letters before the first '-' (REQ, M, ...)
  // anything else (file paths, "SC 3.1", releases) falls back to "other"
  const m = id.match(/^([A-Z]+)-/);
  return (m && COLORS[m[1]]) ? m[1] : "other";
}
G.nodes.forEach(n => { n.color = COLORS[prefix(n.id)]; });

// ---- force layout ---------------------------------------------------------
const W0 = 1600, H0 = 1000;
G.nodes.forEach((n, i) => {
  // deterministic-ish start: golden-angle spiral
  const a = i * 2.399963, r = 6 * Math.sqrt(i);
  n.x = W0 / 2 + r * Math.cos(a);
  n.y = H0 / 2 + r * Math.sin(a);
  n.vx = 0; n.vy = 0; n.pinned = false;
});

// degree of each node (edge count, both directions)
const degree = new Map(G.nodes.map(n => [n.id, 0]));
G.edges.forEach(e => {
  degree.set(e.from, degree.get(e.from) + 1);
  degree.set(e.to, degree.get(e.to) + 1);
});

// find connected components
const compOf = new Map(), comps = [];
{
  const seen = new Set();
  for (const n of G.nodes) {
    if (seen.has(n.id)) continue;
    const comp = [], stack = [n.id];
    while (stack.length) {
      const id = stack.pop();
      if (seen.has(id)) continue;
      seen.add(id); comp.push(id);
      adj.get(id).forEach(a => { if (!seen.has(a.other)) stack.push(a.other); });
    }
    comps.push(comp);
  }
  comps.sort((x, y) => y.length - x.length);
  comps.forEach((comp, ci) => comp.forEach(id => compOf.set(id, ci)));
}

// detect communities inside the graph using label propagation
const community = new Map(G.nodes.map(n => [n.id, n.id]));
for (let iter = 0; iter < 15; iter++) {
  let changed = 0;
  for (const n of G.nodes) {
    const nbs = adj.get(n.id);
    if (!nbs.length) continue;
    const counts = {};
    for (const a of nbs) {
      const c = community.get(a.other);
      counts[c] = (counts[c] || 0) + 1;
    }
    let maxC = community.get(n.id), maxCount = 0;
    for (const [c, cnt] of Object.entries(counts)) {
      if (cnt > maxCount) { maxCount = cnt; maxC = c; }
    }
    if (maxC !== community.get(n.id)) { community.set(n.id, maxC); changed++; }
  }
  if (!changed) break;
}

// initial layout: group communities radially, place disconnected islands in outer orbit
{
  const coreComms = new Map();
  comps[0].forEach(id => {
    const c = community.get(id);
    if (!coreComms.has(c)) coreComms.set(c, []);
    coreComms.get(c).push(byId.get(id));
  });
  const sortedCoreComms = [...coreComms.values()].sort((a, b) => b.length - a.length);
  const numBig = sortedCoreComms.filter(c => c.length >= 3).length || 1;
  let bigIdx = 0, smallIdx = 0;
  sortedCoreComms.forEach(commNodes => {
    let cx, cy;
    if (commNodes.length >= 3) {
      const angle = (bigIdx / numBig) * Math.PI * 2;
      const r = 160 + (bigIdx % 2) * 50;
      cx = W0 / 2 + r * Math.cos(angle);
      cy = H0 / 2 + r * Math.sin(angle);
      bigIdx++;
    } else {
      const angle = (smallIdx / (sortedCoreComms.length - numBig || 1)) * Math.PI * 2;
      cx = W0 / 2 + 270 * Math.cos(angle);
      cy = H0 / 2 + 270 * Math.sin(angle);
      smallIdx++;
    }
    commNodes.forEach((n, k) => {
      const a = k * 2.399963, r = 10 * Math.sqrt(k);
      n.x = cx + r * Math.cos(a);
      n.y = cy + r * Math.sin(a);
      n.vx = 0; n.vy = 0; n.pinned = false;
    });
  });

  const islands = [];
  for (let ci = 1; ci < comps.length; ci++) comps[ci].forEach(id => islands.push(byId.get(id)));
  islands.forEach((n, i) => {
    const a = (i / islands.length) * Math.PI * 2;
    const r = 390 + (i % 3) * 18;
    n.x = W0 / 2 + r * Math.cos(a);
    n.y = H0 / 2 + r * Math.sin(a);
    n.vx = 0; n.vy = 0; n.pinned = false;
  });
}

// force parameters: bounded local repulsion + annealing prevents slingshots
const MAX_REP_DIST = 180, REP = 1800, SPRING_K = 0.14, REST_LEN = 32, CENTER_K = 0.01;
const DAMP = 0.82, ALPHA_DECAY = 0.993, MAX_V = 10;
let alpha = 1.0;
let simRunning = false, simTicks = 0, simTimer = null;
const MAX_TICKS = 1500;
let userViewModified = false;

function simTick() {
  const nodes = G.nodes;
  const edges = G.edges;
  const forces = new Float64Array(nodes.length * 2);

  // local repulsion with distance cap and softening
  for (let i = 0; i < nodes.length; i++) {
    const a = nodes[i];
    for (let j = i + 1; j < nodes.length; j++) {
      const b = nodes[j];
      let dx = a.x - b.x, dy = a.y - b.y;
      let d2 = dx * dx + dy * dy;
      if (d2 > MAX_REP_DIST * MAX_REP_DIST) continue;
      const d = Math.sqrt(Math.max(d2, 1.0));
      const f = REP / (d * d + 64);
      const fx = (dx / d) * f, fy = (dy / d) * f;
      forces[i * 2] += fx; forces[i * 2 + 1] += fy;
      forces[j * 2] -= fx; forces[j * 2 + 1] -= fy;
    }
  }

  // spring attraction along edges
  for (const e of edges) {
    const a = byId.get(e.from), b = byId.get(e.to);
    const dx = b.x - a.x, dy = b.y - a.y;
    const d = Math.max(0.1, Math.hypot(dx, dy));
    const f = SPRING_K * (d - REST_LEN);
    const fx = (dx / d) * f, fy = (dy / d) * f;
    forces[a.index * 2] += fx; forces[a.index * 2 + 1] += fy;
    forces[b.index * 2] -= fx; forces[b.index * 2 + 1] -= fy;
  }

  let maxMove = 0;
  for (let i = 0; i < nodes.length; i++) {
    const n = nodes[i];
    const isIsland = compOf.get(n.id) > 0;
    if (isIsland) {
      const dist = Math.hypot(n.x - W0 / 2, n.y - H0 / 2);
      const pull = 0.03 * (dist - 400);
      const ang = Math.atan2(n.y - H0 / 2, n.x - W0 / 2);
      forces[i * 2] -= pull * Math.cos(ang);
      forces[i * 2 + 1] -= pull * Math.sin(ang);
    } else {
      forces[i * 2] += (W0 / 2 - n.x) * CENTER_K;
      forces[i * 2 + 1] += (H0 / 2 - n.y) * CENTER_K;
    }

    if (!n.pinned) {
      n.vx = (n.vx + forces[i * 2] * alpha) * DAMP;
      n.vy = (n.vy + forces[i * 2 + 1] * alpha) * DAMP;
      const v = Math.hypot(n.vx, n.vy);
      if (v > MAX_V) { n.vx = (n.vx / v) * MAX_V; n.vy = (n.vy / v) * MAX_V; }
      n.x += n.vx; n.y += n.vy;
      if (v > maxMove) maxMove = v;
    } else { n.vx = 0; n.vy = 0; }
  }

  alpha *= ALPHA_DECAY;
  simTicks++;
  if (simTicks >= MAX_TICKS || (alpha < 0.005 && maxMove < 0.08)) stopSim();
}

function runSim() {
  if (simRunning) return;
  simRunning = true;
  simTimer = setInterval(() => {
    for (let k = 0; k < 4 && simRunning; k++) simTick();
    draw();
  }, 16);
}
function stopSim() {
  simRunning = false;
  if (simTimer !== null) { clearInterval(simTimer); simTimer = null; }
  if (!userViewModified) fitView();
  draw();
  status();
}
runSim();

// ---- canvas / view --------------------------------------------------------
const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");
let view = { x: 0, y: 0, scale: 1 };  // world->screen: s = (w - view.*) * scale

function resize() {
  const dpr = window.devicePixelRatio || 1;
  canvas.width = canvas.clientWidth * dpr;
  canvas.height = canvas.clientHeight * dpr;
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  draw();
}
window.addEventListener("resize", resize);

function fitView() {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  for (const n of G.nodes) {
    x0 = Math.min(x0, n.x); y0 = Math.min(y0, n.y);
    x1 = Math.max(x1, n.x); y1 = Math.max(y1, n.y);
  }
  const pad = 60;
  const w = canvas.clientWidth, h = canvas.clientHeight;
  const s = Math.min(w / (x1 - x0 + 2 * pad), h / (y1 - y0 + 2 * pad), 2);
  view.scale = s;
  view.x = (x0 + x1) / 2 - w / 2 / s;
  view.y = (y0 + y1) / 2 - h / 2 / s;
}

function toScreen(n) {
  return [(n.x - view.x) * view.scale, (n.y - view.y) * view.scale];
}

// ---- interaction state ----------------------------------------------------
let selected = null;           // selected node object
let hover = null;
let matches = [], matchIdx = -1;
let neighborsOfSelected = null;

function nodeAt(mx, my) {
  const r = 8 / Math.sqrt(view.scale) + 2;
  for (let i = G.nodes.length - 1; i >= 0; i--) {
    const n = G.nodes[i];
    const [sx, sy] = toScreen(n);
    if ((sx - mx) ** 2 + (sy - my) ** 2 <= r * r) return n;
  }
  return null;
}

// ---- rendering ------------------------------------------------------------
function draw() {
  const w = canvas.clientWidth, h = canvas.clientHeight;
  ctx.clearRect(0, 0, w, h);

  const matchSet = new Set(matches);
  const dimUnmatched = matches.length > 0;

  // edges
  const hasSelection = !!selected;

  // pass 1: normal / background edges
  ctx.lineWidth = 1.2;
  for (const e of G.edges) {
    if (!visibleTypes.has(e.type)) continue;
    const isInc = hasSelection && (e.from === selected.id || e.to === selected.id);
    if (isInc) continue; // draw later on top

    const a = byId.get(e.from), b = byId.get(e.to);
    const [ax, ay] = toScreen(a), [bx, by] = toScreen(b);

    // base visibility: "halb deutlich" (0.42), dimmed to 0.16 when a node is selected
    let alpha = hasSelection ? 0.16 : 0.42;
    if (dimUnmatched && !(matchSet.has(e.from) || matchSet.has(e.to)))
      alpha = Math.min(alpha, 0.06);

    ctx.strokeStyle = "rgba(145,158,175," + alpha + ")";
    ctx.beginPath(); ctx.moveTo(ax, ay); ctx.lineTo(bx, by); ctx.stroke();
  }

  // pass 2: incident edges of selected node (drawn on top, prominent and bold)
  if (hasSelection) {
    ctx.lineWidth = 2.4;
    for (const e of G.edges) {
      if (!visibleTypes.has(e.type)) continue;
      const isInc = (e.from === selected.id || e.to === selected.id);
      if (!isInc) continue;

      const a = byId.get(e.from), b = byId.get(e.to);
      const [ax, ay] = toScreen(a), [bx, by] = toScreen(b);

      ctx.strokeStyle = "#8bb8ff";
      ctx.beginPath(); ctx.moveTo(ax, ay); ctx.lineTo(bx, by); ctx.stroke();

      // distinct arrowhead towards 'to'
      const ang = Math.atan2(by - ay, bx - ax), L = 8;
      ctx.beginPath();
      ctx.moveTo(bx, by);
      ctx.lineTo(bx - L * Math.cos(ang - 0.45), by - L * Math.sin(ang - 0.45));
      ctx.moveTo(bx, by);
      ctx.lineTo(bx - L * Math.cos(ang + 0.45), by - L * Math.sin(ang + 0.45));
      ctx.stroke();
    }
  }

  // nodes
  const showLabels = view.scale > 0.9;
  for (const n of G.nodes) {
    const [sx, sy] = toScreen(n);
    if (sx < -20 || sy < -20 || sx > w + 20 || sy > h + 20) continue;
    const isMatch = matchSet.has(n.id);
    const isSel = n === selected;
    const isNb = neighborsOfSelected && neighborsOfSelected.has(n.id);
    let alpha = 1;
    if (dimUnmatched && !isMatch) alpha = 0.18;
    else if (hasSelection && !isSel && !isNb) alpha = 0.35;
    ctx.globalAlpha = alpha;
    ctx.fillStyle = n.color;
    ctx.beginPath();
    ctx.arc(sx, sy, isSel ? 8 : (isNb ? 6 : 5), 0, Math.PI * 2);
    ctx.fill();
    if (isSel || isNb || n === hover) {
      ctx.lineWidth = isSel ? 2.5 : 1.8;
      ctx.strokeStyle = isSel ? "#ffffff" : "rgba(255,255,255,0.85)";
      ctx.beginPath(); ctx.arc(sx, sy, isSel ? 10 : 8, 0, Math.PI * 2); ctx.stroke();
    }
    if (isMatch) {
      ctx.lineWidth = 2;
      ctx.strokeStyle = "#ffd54a";
      ctx.beginPath(); ctx.arc(sx, sy, 11, 0, Math.PI * 2); ctx.stroke();
    }
    if (showLabels || isSel || isNb || n === hover || isMatch) {
      ctx.fillStyle = (dimUnmatched && !isMatch) || (hasSelection && !isSel && !isNb && !isMatch)
        ? "rgba(216,222,230,0.4)"
        : "#d8dee6";
      ctx.font = isSel ? "bold 12px 'Segoe UI', system-ui, sans-serif"
                       : (isNb ? "600 11px 'Segoe UI', system-ui, sans-serif" : "11px 'Segoe UI', system-ui, sans-serif");
      ctx.fillText(n.id, sx + 9, sy - 6);
    }
    ctx.globalAlpha = 1;
  }
}

// ---- status ---------------------------------------------------------------
function status() {
  document.getElementById("status").textContent =
    G.nodes.length + " nodes, " + G.edges.length + " edges" +
    (simRunning ? " - layout running (tick " + simTicks + ")..."
                : " - layout settled after " + simTicks + " ticks") +
    " | wheel: zoom, drag background: pan, drag node: move, click node: details";
}

// ---- mouse interaction ----------------------------------------------------
let dragging = null, panning = null, moved = 0;

canvas.addEventListener("mousedown", ev => {
  const n = nodeAt(ev.offsetX, ev.offsetY);
  moved = 0;
  if (n) { dragging = n; n.pinned = true; }
  else { panning = { x: ev.clientX, y: ev.clientY };
         canvas.classList.add("grabbing"); }
});
window.addEventListener("mousemove", ev => {
  if (dragging) {
    dragging.x = view.x + ev.offsetX / view.scale;
    dragging.y = view.y + ev.offsetY / view.scale;
    moved++;
    if (!simRunning) draw();
  } else if (panning) {
    userViewModified = true;
    view.x -= (ev.clientX - panning.x) / view.scale;
    view.y -= (ev.clientY - panning.y) / view.scale;
    panning = { x: ev.clientX, y: ev.clientY };
    moved++;
    draw();
  } else {
    const n = nodeAt(ev.offsetX, ev.offsetY);
    if (n !== hover) { hover = n; canvas.style.cursor = n ? "pointer" : "grab"; draw(); }
  }
});
window.addEventListener("mouseup", ev => {
  if (dragging) {
    dragging.pinned = false;
    if (moved < 4) selectNode(dragging);
    dragging = null;
  }
  if (panning) {
    canvas.classList.remove("grabbing");
    if (moved < 4 && !nodeAt(ev.offsetX, ev.offsetY)) selectNode(null);
    panning = null;
  }
});
canvas.addEventListener("wheel", ev => {
  ev.preventDefault();
  userViewModified = true;
  const f = ev.deltaY < 0 ? 1.15 : 1 / 1.15;
  const mx = ev.offsetX, my = ev.offsetY;
  view.x = mx / view.scale + view.x - mx / (view.scale * f);
  view.y = my / view.scale + view.y - my / (view.scale * f);
  view.scale *= f;
  draw();
}, { passive: false });
canvas.addEventListener("dblclick", () => { userViewModified = false; fitView(); draw(); });

// ---- selection / side panel ----------------------------------------------
function selectNode(n) {
  selected = n;
  neighborsOfSelected = n ? new Set(adj.get(n.id).map(a => a.other)) : null;
  const panel = document.getElementById("sidepanel");
  if (!n) { panel.classList.remove("open"); draw(); return; }
  panel.classList.add("open");
  document.getElementById("sp-id").textContent = n.id;
  document.getElementById("sp-type").textContent = "(" + (n.type || "?") + ")";
  document.getElementById("sp-title").textContent = n.title || "";
  // register entry text (graph.json 'excerpt'); hidden for nodes without one
  const exEl = document.getElementById("sp-excerpt");
  exEl.textContent = n.excerpt || "";
  exEl.style.display = n.excerpt ? "" : "none";
  // group edges by (dir, type), like query_graph.py grouped()
  const groups = new Map();
  for (const a of adj.get(n.id)) {
    const key = a.dir + " " + a.type;
    if (!groups.has(key)) groups.set(key, []);
    const lst = groups.get(key);
    if (!lst.includes(a.other)) lst.push(a.other);
  }
  const body = document.getElementById("sp-body");
  body.innerHTML = "";
  for (const key of [...groups.keys()].sort()) {
    const ids = groups.get(key);
    const div = document.createElement("div");
    div.className = "edge-group";
    const hdr = document.createElement("div");
    hdr.innerHTML = "<span class='edge-type'></span>(" + ids.length + ")";
    hdr.querySelector(".edge-type").textContent = key;
    div.appendChild(hdr);
    const line = document.createElement("div");
    ids.forEach((id, i) => {
      if (i) line.appendChild(document.createTextNode(", "));
      const a = document.createElement("a");
      a.className = "node-link";
      a.textContent = id;
      a.addEventListener("click", () => focusNode(byId.get(id)));
      line.appendChild(a);
    });
    div.appendChild(line);
    body.appendChild(div);
  }
  draw();
}
document.getElementById("sp-close").addEventListener("click", () => selectNode(null));

function focusNode(n) {
  if (!n) return;
  selectNode(n);
  // center view on the node without changing zoom
  view.x = n.x - canvas.clientWidth / 2 / view.scale;
  view.y = n.y - canvas.clientHeight / 2 / view.scale;
  draw();
}

// ---- search ---------------------------------------------------------------
const searchEl = document.getElementById("search");
const matchInfoEl = document.getElementById("matchinfo");

function updateSearch() {
  const q = searchEl.value.trim().toLowerCase();
  matches = []; matchIdx = -1;
  if (q) {
    // exact id matches first, then id fragments, then title fragments
    const exact = [], frag = [], title = [];
    for (const n of G.nodes) {
      const id = n.id.toLowerCase();
      if (id === q) exact.push(n.id);
      else if (id.includes(q)) frag.push(n.id);
      else if ((n.title || "").toLowerCase().includes(q)) title.push(n.id);
    }
    matches = exact.concat(frag, title);
  }
  matchInfoEl.textContent = q
    ? (matches.length ? "1/" + matches.length : "no match") : "";
  if (matches.length) {
    matchIdx = 0;
    matchInfoEl.textContent = "1/" + matches.length;
    focusNode(byId.get(matches[0]));
  } else {
    draw();
  }
}
searchEl.addEventListener("input", updateSearch);
searchEl.addEventListener("keydown", ev => {
  if (ev.key === "Enter" && matches.length) {
    ev.preventDefault();
    matchIdx = (matchIdx + 1) % matches.length;
    matchInfoEl.textContent = (matchIdx + 1) + "/" + matches.length;
    focusNode(byId.get(matches[matchIdx]));
  } else if (ev.key === "Escape") {
    searchEl.value = ""; updateSearch();
  }
});

// ---- legend / filters -----------------------------------------------------
(function buildLegend() {
  const rows = document.getElementById("legendrows");
  const used = new Set(G.nodes.map(n => prefix(n.id)));
  for (const key of Object.keys(COLORS)) {
    if (key !== "other" && !used.has(key)) continue;
    const row = document.createElement("div");
    row.className = "row";
    const dot = document.createElement("span");
    dot.className = "dot";
    dot.style.background = COLORS[key];
    const label = document.createElement("span");
    label.textContent = key;
    row.append(dot, label);
    rows.appendChild(row);
  }
})();

(function buildFilters() {
  const rows = document.getElementById("filterrows");
  const counts = {};
  for (const e of G.edges) counts[e.type] = (counts[e.type] || 0) + 1;
  for (const t of edgeTypes) {
    const label = document.createElement("label");
    const cb = document.createElement("input");
    cb.type = "checkbox"; cb.checked = true;
    cb.addEventListener("change", () => {
      if (cb.checked) visibleTypes.add(t); else visibleTypes.delete(t);
      draw();
    });
    const span = document.createElement("span");
    span.textContent = t + " (" + counts[t] + ")";
    label.append(cb, span);
    rows.appendChild(label);
  }
})();

// ---- init -----------------------------------------------------------------
resize();
fitView();
draw();
status();
</script>
</body>
</html>
"""


def main(argv):
    src = ROOT / "graph.json"
    if not src.exists():
        print("graph.json not found - run: python tools/build_index.py",
              file=sys.stderr)
        sys.exit(1)
    g = json.loads(src.read_text(encoding="utf-8"))
    data = json.dumps(g, ensure_ascii=False, separators=(",", ":"))
    # keep the JSON from accidentally closing the <script> tag
    data = data.replace("</", "<\\/")
    html = (HTML.replace("__DATA__", data)
                .replace("__COLORS__", json.dumps(COLORS)))
    out = ROOT / "graph.html"
    out.write_text(html, encoding="utf-8")
    print(f"wrote {out} ({len(g['nodes'])} nodes, {len(g['edges'])} edges, "
          f"{out.stat().st_size} bytes)")


if __name__ == "__main__":
    main(sys.argv)
