#!/usr/bin/env python3
"""Query graph.json (generated by tools/build_index.py).

Usage:
  python tools/query_graph.py neighbors <ID>      edges both ways, by type
  python tools/query_graph.py impact <ID>         transitive re-check set
  python tools/query_graph.py path <ID1> <ID2>    shortest path (undirected)
  python tools/query_graph.py uncovered [--type T]  nodes without an edge type
  python tools/query_graph.py briefing <ID>       paste-ready context block

Exit 1 on unknown ID, missing graph.json or bad usage. Python stdlib only.

impact semantics: an edge type defines which endpoint DEPENDS on the other
(DEPENDS_ON below); impact walks from the changed ID to everything that
transitively depends on it. 'affects' (CHG history) is excluded - a change
log entry never needs re-checking.
"""
# type: ignore
# ruff: noqa
# pyright: basic

import json
import sys
from collections import defaultdict, deque
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

USAGE = __doc__.strip().splitlines()[2:9]

# which endpoint of an edge depends on the other (None: no dependency)
DEPENDS_ON = {
    "closes": "from",        # the OQ resolution rests on the DEC
    "decides": "from",       # the DEC interprets/shapes the REQ
    "amends": "from",
    "supersedes": "from",
    "links": "from",
    "covers": "to",          # the concept section covers the REQ
    "allocated_to": "to",    # SUB/IF implement the REQ
    "tested_by": "to",       # TC/test file verifies the REQ or IF
    "in_release": "to",      # the release plan carries the REQ
    "affects": None,         # history - never a re-check target
}

CAP = 50  # max ids listed per group


def load():
    path = ROOT / "graph.json"
    if not path.exists():
        print("graph.json not found - run: python tools/build_index.py",
              file=sys.stderr)
        sys.exit(1)
    g = json.loads(path.read_text(encoding="utf-8"))
    nodes = {n["id"]: n for n in g["nodes"]}
    out = defaultdict(list)   # id -> [(type, other, dir)] dir: '->' edge leaves id
    inc = defaultdict(list)
    for e in g["edges"]:
        out[e["from"]].append((e["type"], e["to"]))
        inc[e["to"]].append((e["type"], e["from"]))
    return g, nodes, out, inc


def need(nodes, nid):
    if nid not in nodes:
        print(f"unknown ID: {nid}", file=sys.stderr)
        sys.exit(1)


def label(nodes, nid):
    n = nodes.get(nid, {})
    return f"{nid} ({n.get('type', '?')})" + (
        f": {n['title']}" if n.get("title") else "")


def grouped(nodes, pairs):
    """pairs = [(dir, type, other)] -> {('->', type): [other...]} sorted."""
    by = defaultdict(list)
    for d, t, o in pairs:
        if o not in by[(d, t)]:
            by[(d, t)].append(o)
    return dict(sorted(by.items()))


def show_groups(nodes, groups, indent=""):
    lines = []
    for (d, t), ids in groups.items():
        shown = ids[:CAP]
        more = f" +{len(ids) - CAP} more" if len(ids) > CAP else ""
        lines.append(f"{indent}{d} {t} ({len(ids)}): {', '.join(shown)}{more}")
    return lines


def neighbor_pairs(nid, out, inc):
    return ([("->", t, o) for t, o in out[nid]] +
            [("<-", t, o) for t, o in inc[nid]])


def cmd_neighbors(nodes, out, inc, nid):
    need(nodes, nid)
    print(label(nodes, nid))
    for line in show_groups(nodes, grouped(nodes, neighbor_pairs(nid, out, inc)),
                            indent="  "):
        print(line)


def cmd_briefing(nodes, out, inc, nid):
    need(nodes, nid)
    n = nodes[nid]
    print(f"## Briefing {nid}" + (f" - {n['title']}" if n.get("title") else ""))
    print(f"Type: {n.get('type', '?')} (from graph.json, generated - "
          f"source: registers)")
    for (d, t), ids in grouped(nodes, neighbor_pairs(nid, out, inc)).items():
        arrow = "out" if d == "->" else "in "
        print(f"- {t} ({arrow}, {len(ids)}): {', '.join(ids[:CAP])}"
              + (f" +{len(ids) - CAP} more" if len(ids) > CAP else ""))


def cmd_impact(nodes, out, inc, nid):
    need(nodes, nid)
    # dependent edges per node: edge (f -ty-> t), dependency per DEPENDS_ON
    dep = defaultdict(list)  # depended-upon id -> [(type, dependent id)]
    for frm, lst in out.items():
        for ty, to in lst:
            d = DEPENDS_ON.get(ty)
            if d == "from":
                dep[to].append((ty, frm))
            elif d == "to":
                dep[frm].append((ty, to))
    seen, depth = {nid}, {nid: 0}
    queue = deque([nid])
    while queue:
        cur = queue.popleft()
        for ty, nxt in dep[cur]:
            if nxt not in seen:
                seen.add(nxt)
                depth[nxt] = depth[cur] + 1
                queue.append(nxt)
    by_type = defaultdict(list)
    for x in sorted(seen - {nid}, key=lambda x: (depth[x], x)):
        by_type[nodes.get(x, {}).get("type", "?")].append(x)
    print(f"impact {nid}: {len(seen) - 1} nodes to re-check on change")
    for t, ids in sorted(by_type.items()):
        shown = ids[:CAP]
        more = f" +{len(ids) - CAP} more" if len(ids) > CAP else ""
        print(f"  {t} ({len(ids)}): {', '.join(shown)}{more}")


def cmd_path(nodes, out, inc, a, b):
    need(nodes, a)
    need(nodes, b)
    adj = defaultdict(list)  # id -> [(other, type, dir-from-id)]
    for frm, lst in out.items():
        for ty, to in lst:
            adj[frm].append((to, ty, "->"))
            adj[to].append((frm, ty, "<-"))
    prev = {a: None}
    queue = deque([a])
    while queue and b not in prev:
        cur = queue.popleft()
        for nxt, ty, d in adj[cur]:
            if nxt not in prev:
                prev[nxt] = (cur, ty, d)
                queue.append(nxt)
    if b not in prev:
        print(f"no path between {a} and {b}")
        return
    hops = []
    cur = b
    while prev[cur] is not None:
        p, ty, d = prev[cur]
        hops.append((p, ty, d, cur) if d == "->" else (cur, ty, "<-", p))
        cur = p
    hops.reverse()
    print(f"path {a} -> {b}: {len(hops)} hop(s)")
    for frm, ty, d, to in hops:
        if d == "->":
            print(f"  {frm} -[{ty}]-> {to}")
        else:
            print(f"  {to} <-[{ty}]- {frm}")


def cmd_uncovered(g, nodes, out, inc, etype):
    types = ([etype] if etype else
             ["covers", "allocated_to", "tested_by", "decides"])
    for ty in types:
        have = set()
        for e in g["edges"]:
            if e["type"] == ty:
                have.add(e["from"])
                have.add(e["to"])
        missing = defaultdict(list)
        for nid, n in nodes.items():
            if nid not in have:
                missing[n.get("type", "?")].append(nid)
        total = sum(len(v) for v in missing.values())
        print(f"uncovered [{ty}]: {total} node(s) without a '{ty}' edge")
        for nt, ids in sorted(missing.items()):
            ids.sort()
            shown = ids[:CAP]
            more = f" +{len(ids) - CAP} more" if len(ids) > CAP else ""
            print(f"  {nt} ({len(ids)}): {', '.join(shown)}{more}")


def main(argv):
    if len(argv) < 2 or argv[1] in ("-h", "--help"):
        print("\n".join(USAGE))
        sys.exit(0 if len(argv) >= 2 else 1)
    cmd, args = argv[1], argv[2:]
    g, nodes, out, inc = load()
    if cmd == "neighbors" and len(args) == 1:
        cmd_neighbors(nodes, out, inc, args[0])
    elif cmd == "impact" and len(args) == 1:
        cmd_impact(nodes, out, inc, args[0])
    elif cmd == "path" and len(args) == 2:
        cmd_path(nodes, out, inc, args[0], args[1])
    elif cmd == "briefing" and len(args) == 1:
        cmd_briefing(nodes, out, inc, args[0])
    elif cmd == "uncovered" and (not args or
                                 (len(args) == 2 and args[0] == "--type")):
        cmd_uncovered(g, nodes, out, inc, args[1] if args else None)
    else:
        print("\n".join(USAGE), file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main(sys.argv)
